#!/usr/bin/env bash
#
# product-stack.sh
# -----------------------------------------------------------------------------
# Per-product Docker Compose stack manager. Runs on the WSL host (or any Linux
# box with Docker). Generates a per-product docker-compose.override.yml +
# .env in ~/.auto-board-stacks/<slug>/ that namespaces container names and
# remaps ports based on port-registry.json. This lets multiple products run
# docker-compose simultaneously on the same host without collisions.
#
# WHY: the duo-admin template's docker-compose.yml uses fixed container names
# (duolabs_postgres, duolabs_minio, etc.) and fixed ports (5432, 9000, etc.).
# Two products forked from the template would collide on container names AND
# host ports. We don't want to modify the template per fork, so we use
# Docker Compose's override + COMPOSE_PROJECT_NAME conventions to namespace
# externally.
#
# Usage:
#   product-stack.sh setup <product-slug> <product-repo-path>
#       Generate ~/.auto-board-stacks/<slug>/{docker-compose.override.yml,.env}
#       (idempotent — re-run safe)
#
#   product-stack.sh up <product-slug> <product-repo-path>
#       Boot the stack (containers up). Uses COMPOSE_PROJECT_NAME=<slug>
#       so containers/networks/volumes are namespaced.
#
#   product-stack.sh down <product-slug> <product-repo-path>
#       Stop the stack (preserves volumes).
#
#   product-stack.sh nuke <product-slug> <product-repo-path>
#       Stop + remove volumes (DESTRUCTIVE — loses DB data).
#
#   product-stack.sh status <product-slug>
#       Print stack status (running containers + DATABASE_URL).
#
#   product-stack.sh database-url <product-slug>
#       Print the DATABASE_URL agents should use.
#
# Designed to be invoked from the agent's workdir on the WSL host:
#   cd $WORKDIR && product-stack.sh up duozada $WORKDIR
#
# Or remotely from the Mac via SSH:
#   ssh wsl 'product-stack.sh up duozada /home/.../duozada'
# -----------------------------------------------------------------------------

set -euo pipefail

ACTION="${1:?Usage: $0 <setup|up|down|nuke|status|database-url> <product-slug> [product-repo-path]}"
SLUG="${2:?Usage: $0 $ACTION <product-slug> [product-repo-path]}"
PRODUCT_REPO="${3:-}"

REGISTRY_PATH="${REGISTRY_PATH:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/port-registry.json}"
STACK_ROOT="${STACK_ROOT:-$HOME/.auto-board-stacks}"
STACK_DIR="${STACK_ROOT}/${SLUG}"

require() { command -v "$1" >/dev/null 2>&1 || { echo "❌ Missing: $1" >&2; exit 1; }; }
require docker
require jq

if [[ ! -f "$REGISTRY_PATH" ]]; then
  echo "❌ Port registry not found: $REGISTRY_PATH" >&2
  exit 1
fi

# ─── Read port allocation for this product ──────────────────────────────────
PORTS_JSON=$(jq --arg s "$SLUG" '.products[$s] // empty' "$REGISTRY_PATH")
if [[ -z "$PORTS_JSON" || "$PORTS_JSON" == "null" ]]; then
  echo "❌ Product '$SLUG' not in $REGISTRY_PATH." >&2
  echo "   Add it with the next available offset:" >&2
  echo "     jq '.products.$SLUG = {\"offset\": .\"\$next_available_offset\", \"postgres\": (5432 + (.\"\$next_available_offset\"*10)), ...}' $REGISTRY_PATH" >&2
  echo "   Or copy the duozada entry and shift ports by 10*N." >&2
  exit 1
fi

POSTGRES_PORT=$(echo "$PORTS_JSON" | jq -r '.postgres')
POSTGRES_TEST_PORT=$(echo "$PORTS_JSON" | jq -r '.postgres_test')
MINIO_API_PORT=$(echo "$PORTS_JSON" | jq -r '.minio_api')
MINIO_CONSOLE_PORT=$(echo "$PORTS_JSON" | jq -r '.minio_console')
MAILPIT_SMTP_PORT=$(echo "$PORTS_JSON" | jq -r '.mailpit_smtp')
MAILPIT_UI_PORT=$(echo "$PORTS_JSON" | jq -r '.mailpit_ui')

# ─── Compute paths ──────────────────────────────────────────────────────────
OVERRIDE_PATH="${STACK_DIR}/docker-compose.override.yml"
ENV_PATH="${STACK_DIR}/.env"
DATABASE_URL="postgresql://postgres:postgres@localhost:${POSTGRES_PORT}/postgres"
DATABASE_TEST_URL="postgresql://postgres:postgres@localhost:${POSTGRES_TEST_PORT}/postgres_test"

# ─── Action: setup ───────────────────────────────────────────────────────────
do_setup() {
  mkdir -p "$STACK_DIR"

  cat > "$OVERRIDE_PATH" <<EOF
# Auto-generated by product-stack.sh — DO NOT EDIT BY HAND
# Per-product namespacing for the auto-board pipeline.
# Product: ${SLUG}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

services:
  postgres:
    container_name: ${SLUG}_postgres
    ports:
      - "${POSTGRES_PORT}:5432"

  postgres-test:
    container_name: ${SLUG}_postgres_test
    ports:
      - "${POSTGRES_TEST_PORT}:5432"

  minio:
    container_name: ${SLUG}_minio
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

  mailpit:
    container_name: ${SLUG}_mailpit
    ports:
      - "${MAILPIT_SMTP_PORT}:1025"
      - "${MAILPIT_UI_PORT}:8025"

volumes:
  postgres_data:
    name: ${SLUG}_postgres_data
  minio_data:
    name: ${SLUG}_minio_data
  # mysql_data declared by template but unused — leaving as-is to match the upstream compose
EOF

  cat > "$ENV_PATH" <<EOF
# Auto-generated by product-stack.sh — DO NOT EDIT BY HAND
COMPOSE_PROJECT_NAME=${SLUG}
DATABASE_URL=${DATABASE_URL}
DATABASE_TEST_URL=${DATABASE_TEST_URL}
S3_ENDPOINT=http://localhost:${MINIO_API_PORT}
S3_REGION=us-east-1
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin
SMTP_HOST=localhost
SMTP_PORT=${MAILPIT_SMTP_PORT}
EOF

  echo "✓ Stack files generated:"
  echo "    Override: $OVERRIDE_PATH"
  echo "    Env:      $ENV_PATH"
  echo "    Database: $DATABASE_URL"
}

# ─── Action: up ──────────────────────────────────────────────────────────────
do_up() {
  if [[ ! -f "$OVERRIDE_PATH" ]]; then
    do_setup
  fi
  if [[ -z "$PRODUCT_REPO" ]]; then
    echo "❌ <product-repo-path> required for 'up'" >&2
    exit 1
  fi
  if [[ ! -f "$PRODUCT_REPO/docker-compose.yml" ]]; then
    echo "❌ docker-compose.yml not found in $PRODUCT_REPO" >&2
    exit 1
  fi

  echo "==> Booting ${SLUG} stack from $PRODUCT_REPO ..."
  ( cd "$PRODUCT_REPO" && \
    COMPOSE_PROJECT_NAME="$SLUG" \
    docker compose \
      -f docker-compose.yml \
      -f "$OVERRIDE_PATH" \
      --env-file "$ENV_PATH" \
      up -d )

  echo "✓ Stack up. DATABASE_URL=${DATABASE_URL}"
}

# ─── Action: down ────────────────────────────────────────────────────────────
do_down() {
  if [[ -z "$PRODUCT_REPO" ]]; then
    echo "❌ <product-repo-path> required for 'down'" >&2
    exit 1
  fi
  ( cd "$PRODUCT_REPO" && \
    COMPOSE_PROJECT_NAME="$SLUG" \
    docker compose \
      -f docker-compose.yml \
      -f "$OVERRIDE_PATH" \
      --env-file "$ENV_PATH" \
      down )
  echo "✓ Stack down (volumes preserved)."
}

# ─── Action: nuke ────────────────────────────────────────────────────────────
do_nuke() {
  if [[ -z "$PRODUCT_REPO" ]]; then
    echo "❌ <product-repo-path> required for 'nuke'" >&2
    exit 1
  fi
  echo "⚠ This will DELETE all data for product ${SLUG}. Containers + volumes."
  ( cd "$PRODUCT_REPO" && \
    COMPOSE_PROJECT_NAME="$SLUG" \
    docker compose \
      -f docker-compose.yml \
      -f "$OVERRIDE_PATH" \
      --env-file "$ENV_PATH" \
      down -v )
  echo "✓ Stack nuked."
}

# ─── Action: status ──────────────────────────────────────────────────────────
do_status() {
  echo "Stack: ${SLUG}"
  echo "  Override: $OVERRIDE_PATH"
  echo "  Env:      $ENV_PATH"
  echo "  DATABASE_URL=${DATABASE_URL}"
  echo
  echo "Containers:"
  docker ps --filter "label=com.docker.compose.project=${SLUG}" \
    --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' || \
  docker ps -a --filter "name=^${SLUG}_" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
}

# ─── Action: database-url ────────────────────────────────────────────────────
do_database_url() {
  echo "$DATABASE_URL"
}

case "$ACTION" in
  setup)         do_setup ;;
  up)            do_up ;;
  down)          do_down ;;
  nuke)          do_nuke ;;
  status)        do_status ;;
  database-url)  do_database_url ;;
  *)             echo "❌ Unknown action: $ACTION" >&2; exit 1 ;;
esac
